
create table if not exists tech_registry (
  id text primary key,
  name text not null,
  owner text,
  repo text,
  search_query text,
  subreddit text,
  stackshare_slug text,
  last_checked timestamp with time zone
);

create table if not exists tech_snapshots (
  id bigint generated by default as identity primary key,
  tech_id text references tech_registry(id),
  tech_name text not null,
  snapshot_date date not null,
  github_metrics jsonb,
  reddit_metrics jsonb,
  hn_metrics jsonb,
  so_metrics jsonb,
  youtube_metrics jsonb,
  stackshare_metrics jsonb,
  google_jobs jsonb,
  deaditude_score numeric,
  component_scores jsonb,
  created_at timestamp with time zone default now()
);