-- Migration for the tech_projects table
CREATE TABLE IF NOT EXISTS tech_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tech_id TEXT REFERENCES tech_registry(id) NOT NULL,
  name TEXT NOT NULL,
  url TEXT,
  github_url TEXT,
  description TEXT NOT NULL,
  self_roast TEXT NOT NULL,
  screenshot_url TEXT,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  approved_at TIMESTAMP WITH TIME ZONE
);

-- Create index for faster lookups by tech_id
CREATE INDEX IF NOT EXISTS idx_tech_projects_tech_id ON tech_projects(tech_id);

-- Create index for showing approved projects
CREATE INDEX IF NOT EXISTS idx_tech_projects_approved ON tech_projects(is_approved); 